accounts/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import re_path
from accounts import views

urlpatterns = [
    re_path(r'^send_login_email$', views.send_login_email, name='send_login_email'),
    re_path(r'^login$', views.login, name='login'),
    re_path(r'^logout$', LogoutView.as_view(), name='logout'),
]

lists/urls.py
from django.contrib import admin
from django.urls import re_path
from lists import views

urlpatterns = [
    re_path(r'^new$', views.NewListView.as_view(), name='new_list'),
    re_path(r'^(?P<pk>\d+)/$', views.ViewAndAddToList.as_view(), name='view_list'),
    re_path(r'^(\d+)/share$', views.share_list, name='share_list'),
    re_path(r'^users/(.+)/$', views.my_lists, name='my_lists'),
]

superlists/urls.py
from django.urls import re_path
from lists import views as list_views
from lists import urls as list_urls
from django.conf.urls import include
from accounts import urls as accounts_urls
from lists.api import router

urlpatterns = [
    re_path(r'^$', list_views.HomePageView.as_view(), name='home'),
    re_path(r'^lists/', include(list_urls)),
    re_path(r'^accounts/', include(accounts_urls)),
    re_path(r'^api/', include(router.urls)),
]

accounts/models.py
from django.db import models
from django.contrib import auth
import uuid

auth.signals.user_logged_in.disconnect(auth.models.update_last_login)

class User(models.Model):
    email = models.EmailField(primary_key=True)
    REQUIRED_FIELDS = []
    USERNAME_FIELD = 'email'
    is_anonymous = False
    is_authenticated = True
    is_active = True

class Token(models.Model):
    email = models.EmailField()
    uid = models.CharField(default=uuid.uuid4, max_length=40)

lists/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings

class List(models.Model):

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, on_delete=models.CASCADE)
    shared_with = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='shared_lists')
    
    def get_absolute_url(self):
        return reverse('view_list', args=[self.id])
    
    @staticmethod
    def create_new(first_item_text, owner=None):
        list_ = List.objects.create(owner=owner)
        Item.objects.create(text=first_item_text, list=list_)
        return list_

    @property
    def name(self):
        return self.item_set.first().text

class Item(models.Model):
    text = models.TextField(default='')
    list = models.ForeignKey(List, default=None, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('list', 'text')
        ordering = ('id',)
    
    def get_absolute_url(self):
        return reverse('view_list', args=[self.list.id])

lists/forms.py
from django import forms
from lists.models import Item, List
from django.core.exceptions import ValidationError

EMPTY_ITEM_ERROR = "You can't have an empty list item"
DUPLICATE_ITEM_ERROR = "You've already got this item in your list"

class ItemForm(forms.models.ModelForm):

    class Meta:
        model = Item
        fields = ('text',)
        widgets = {
            'text': forms.fields.TextInput(attrs={
                'placeholder': 'Enter a to-do item',
                'class': 'form-control input-lg',
            }),
        }
        error_messages = {
            'text': {'required': EMPTY_ITEM_ERROR}
        }

class NewListForm(ItemForm):
    
    def save(self, owner):
        if owner.is_authenticated:
            return List.create_new(first_item_text=self.cleaned_data['text'], owner=owner)
        else:
            return List.create_new(first_item_text=self.cleaned_data['text'])

class ExistingListItemForm(ItemForm):
    
    def __init__(self, for_list, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.instance.list = for_list
    
    def validate_unique(self):
        try:
            self.instance.validate_unique()
        except ValidationError as e:
            e.error_dict = {'text': [DUPLICATE_ITEM_ERROR]}
            self._update_errors(e)

accounts/views.py
from django.shortcuts import render, redirect
from django.core.mail import send_mail
from django.contrib import messages, auth
from accounts.models import Token
from django.urls import reverse

def send_login_email(request):
    email = request.POST['email']
    token = Token.objects.create(email=email)
    url = request.build_absolute_uri(reverse('login') + '?token=' + str(token.uid))
    message_body = f'Use this link to log in:\n\n{url}'
    send_mail(
        'Your login link for Superlists', 
        message_body, 
        'noreply@superlists', 
        [email]
    )
    messages.success(
        request,
        "Check your email, we've sent you a link you can use to log in."
    )
    return redirect('/')

def login(request):
    user = auth.authenticate(request=request, uid=request.GET.get('token'))
    if user:
        auth.login(request=request, user=user)
    return redirect('/')

lists/views.py
from django.shortcuts import render, redirect
from lists.models import List
from lists.forms import ItemForm, ExistingListItemForm, NewListForm
from django.contrib.auth import get_user_model
from django.views.generic import FormView, CreateView, DetailView

User = get_user_model()

class HomePageView(FormView):
    template_name = 'home.html'
    form_class = ItemForm

class NewListView(CreateView):
    form_class = NewListForm
    template_name = 'home.html'

    def form_valid(self, form):
        list_ = form.save(self.request.user)
        return redirect(list_)

class ViewAndAddToList(DetailView, CreateView):
    model = List
    template_name = 'list.html'
    form_class = ExistingListItemForm

    def get_form(self):
        self.object = self.get_object()
        return self.form_class(for_list=self.object, data=self.request.POST)

def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    form = ExistingListItemForm(for_list=list_)

    if request.method == 'POST':
        form = ExistingListItemForm(for_list=list_, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(list_)
    return render(request, 'list.html', {'list': list_, 'form': form})
    
def new_list(request):
    form = NewListForm(data=request.POST)
    if form.is_valid():
        list_ = form.save(owner=request.user)
        return redirect(list_)
    return render(request, 'home.html', {'form': form})
    
def my_lists(request, email):
    owner = User.objects.get(email=email)
    return render(request, 'my_lists.html', {'owner': owner})

def share_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    list_.shared_with.add(request.POST['sharee'])
    return redirect(list_)

lists/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial_scale=1">
        <title>To-Do lists</title>
        <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
        <link href="/static/base.css" rel="stylesheet">
    </head>

    <body>
        <div class="container">

            <nav class="navbar navbar-default" role="navigation">
                <div class="container-fluid">
                  <a class="navbar-brand" href="/">Superlists</a>
                  {% if user.email %}
                    <ul class="nav navbar-nav navbar-left">
                        <li><a href="{% url 'my_lists' user.email %}">My lists</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                      <li class="navbar-text">Logged in as {{ user.email }}</li>
                      <li><a href="{% url 'logout' %}">Log out</a></li>                    
                    </ul>
                  {% else %}
                    <form class="navbar-form navbar-right"
                          method="POST"
                          action="{% url 'send_login_email' %}">
                      <span>Enter email to log in:</span>
                      <input class="form-control" name="email" type="text" />
                      {% csrf_token %}
                    </form>
                  {% endif %}
                </div>
            </nav>

            {% if messages %}
                <div class="row">
                    <div class="col-md-8">
                        {% for message in messages %}
                            {% if message.level_tag == 'success' %}
                                <div class="alert alert-success">{{ message }}</div>
                            {% else %}
                                <div class="alert alert-warning">{{ message }}</div>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            {% endif %}

            <div class="row">
                <div class="jumbotron">
                    <div class="text-center">
                        <h1>{% block header_text %}{% endblock %}</h1>
                        
                        {% block list_table %}
                            <form id="id_item_form" method="POST" action="{% block form_action %}{% endblock %}">
                                {{ form.text }}
                                {% csrf_token %}
                                <div class="form-group has-error">
                                    <div class="help-block">
                                        {% if form.errors %}
                                            {{ form.text.errors }}
                                        {% endif %}
                                    </div>
                                </div>
                            </form>
                        {% endblock %}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    {% block table %}
                    {% endblock %}
                </div>
            </div>

            <div class="row">
                <div class="col">
                    {% block extra_content %}
                    {% endblock %}
                </div>
            </div>
        </div>

        <script src="/static/jquery-3.6.3.js"></script>
        <script src="/static/list.js"></script>

        {% block scripts %}
            <script>
                $(document).ready(function () {
                    window.Superlists.initialize();
                });
            </script>
        {% endblock scripts %}
    </body>
</html>

lists/templates/home.html
{% extends 'base.html' %}

{% block header_text %}Start a new To-Do list{% endblock %}

{% block form_action %}{% url 'new_list' %}{% endblock %}

lists/templates/list.html
{% extends 'base.html' %}

{% block header_text %}Your To-Do list{% endblock %}

{% block form_action %}{% url 'view_list' list.id %}{% endblock %}

{% block table %}
  <table id="id_list_table" class="table">
  </table>

  {% if list.owner %}
    <p>List owner: <span id="id_list_owner">{{ list.owner.email }}</span><p>
  {% endif %}
{% endblock %}

{% block extra_content %}
  <div class="row">

    <div class="col-md-6">
      <h3>Shared with</h3>
      <ul>
        {% for sharee in list.shared_with.all %}
          <li class="list-sharee">{{ sharee.email }}</li>
        {% endfor %}
      </ul>
    </div>

    <div class="col-md-3">
      <h3>Share this list:</h3>
      <form class="form-inline" method="POST" action="{% url 'share_list' list.id %}" >
        {% csrf_token %}
        <input name="sharee" placeholder="your-friend@example.com" />
      </form>
        <h3>Shared with</h3>
        <ul>
            {% for sharee in list.shared_with.all %}
              <li class="list-sharee">{{ sharee.email }}</li>
            {% endfor %}
        </ul>
    </div>
  </div>
{% endblock %}

{% block scripts %}
  <script>
    $(document).ready(function () {
      window.Superlists.initialize({
        listApiUrl: "{% url 'list-detail' list.id %}",
        itemsApiUrl: "{% url 'item-list' %}",
        listId: {{ list.id }},
      });
    });
  </script>
{% endblock scripts %}

lists/templates/my_lists.html
{% extends 'base.html' %}

{% block list_form %}{% endblock %}

{% block header_text %}My Lists{% endblock %}

{% block extra_content %}

    <h2>{{ owner.email }}'s lists</h2>
    <ul>
        {% for list in owner.list_set.all %}
            <li><a href="{{ list.get_absolute_url }}">{{ list.name }}</a></li>
        {% endfor %}
    </ul>

    <h2>Lists shared by other users</h2>
    <ul>
    {% for list in owner.shared_lists.all %}
        <li>
            <a href="{{ list.get_absolute_url }}">{{ list.name }}</a>
            ({{ list.owner.email }})
        </li>
    {% endfor %}
    </ul>

{% endblock %}